version: "2"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "./data:/home/jovyan"
    environment:
      NB_UID: 500
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --NotebookApp.token=''

